name: Schedule Redeploy

on:
  schedule:
    - cron: "*/2 * * * *"  # Runs every 2 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        if: always()
        run: echo "Cron job ran at $(date)"
